### ISSUE TITLE
MTG-Arena-Tool fails to start on Linux due to missing module

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#1077]
With an up-to-date repository and the `npm install` done, Tool fails to run with the following error:

```
$ npm i

> MTG-Arena-Tool@4.2.6 postinstall /home/clement/repositories/MTG-Arena-Tool
> rimraf node_modules/@types/react-native

npm WARN @react-spring/konva@9.0.0-beta.33 requires a peer of konva@>=2.6 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/konva@9.0.0-beta.33 requires a peer of react-konva@>=16.8 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/native@9.0.0-beta.33 requires a peer of react-native@>=0.58 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/three@9.0.0-beta.33 requires a peer of react-three-fiber@>=2.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/three@9.0.0-beta.33 requires a peer of three@>=0.104 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/zdog@9.0.0-beta.33 requires a peer of react-zdog@>=1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @react-spring/zdog@9.0.0-beta.33 requires a peer of zdog@>=1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@16.13.1 requires a peer of react@^16.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1 package from 34 contributors and audited 2116 packages in 16.194s

53 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (5 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
[clement@T470-clement MTG-Arena-Tool]$ npm start

> MTG-Arena-Tool@4.2.6 start /home/clement/repositories/MTG-Arena-Tool
> npm run build && electron .


> MTG-Arena-Tool@4.2.6 prebuild /home/clement/repositories/MTG-Arena-Tool
> npm run clean:lib


> MTG-Arena-Tool@4.2.6 clean:lib /home/clement/repositories/MTG-Arena-Tool
> rimraf lib


> MTG-Arena-Tool@4.2.6 build /home/clement/repositories/MTG-Arena-Tool
> babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/plugins.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/options.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/options.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/bin/babel.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MTG-Arena-Tool@4.2.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clement/.npm/_logs/2020-05-19T17_02_22_495Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MTG-Arena-Tool@4.2.6 start: `npm run build && electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MTG-Arena-Tool@4.2.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clement/.npm/_logs/2020-05-19T17_02_22_557Z-debug.log
```

`2020-05-19T17_02_22_557Z-debug.log` log file:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle MTG-Arena-Tool@4.2.6~prebuild: MTG-Arena-Tool@4.2.6
6 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: PATH: /home/clement/repositories/MTG-Arena-Tool/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-T
ool/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
8 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: CWD: /home/clement/repositories/MTG-Arena-Tool
9 silly lifecycle MTG-Arena-Tool@4.2.6~prebuild: Args: [ '-c', 'npm run clean:lib' ]
10 silly lifecycle MTG-Arena-Tool@4.2.6~prebuild: Returned: code: 0  signal: null
11 info lifecycle MTG-Arena-Tool@4.2.6~build: MTG-Arena-Tool@4.2.6
12 verbose lifecycle MTG-Arena-Tool@4.2.6~build: unsafe-perm in lifecycle true
13 verbose lifecycle MTG-Arena-Tool@4.2.6~build: PATH: /home/clement/repositories/MTG-Arena-Tool/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-Too
l/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
14 verbose lifecycle MTG-Arena-Tool@4.2.6~build: CWD: /home/clement/repositories/MTG-Arena-Tool
15 silly lifecycle MTG-Arena-Tool@4.2.6~build: Args: [
15 silly lifecycle   '-c',
15 silly lifecycle   'babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files'
15 silly lifecycle ]
16 silly lifecycle MTG-Arena-Tool@4.2.6~build: Returned: code: 1  signal: null
17 info lifecycle MTG-Arena-Tool@4.2.6~build: Failed to exec build script
18 verbose stack Error: MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:315:20)
18 verbose stack     at ChildProcess.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:315:20)
18 verbose stack     at maybeClose (internal/child_process.js:1051:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
19 verbose pkgid MTG-Arena-Tool@4.2.6
20 verbose cwd /home/clement/repositories/MTG-Arena-Tool
21 verbose Linux 5.6.11-arch1-1
22 verbose argv "/usr/bin/node" "/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin/npm" "run" "build"
23 verbose node v14.2.0
24 verbose npm  v6.14.5
25 error code ELIFECYCLE
26 error errno 1
27 error MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
27 error Exit status 1
28 error Failed at the MTG-Arena-Tool@4.2.6 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

```
$ npm run build && electron .

> MTG-Arena-Tool@4.2.6 prebuild /home/clement/repositories/MTG-Arena-Tool
> npm run clean:lib


> MTG-Arena-Tool@4.2.6 clean:lib /home/clement/repositories/MTG-Arena-Tool
> rimraf lib


> MTG-Arena-Tool@4.2.6 build /home/clement/repositories/MTG-Arena-Tool
> babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files

Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/plugins.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/options.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/index.js
- /home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/preset-env/lib/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/plugins.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/config/files/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/core/lib/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/options.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/lib/babel/index.js',
    '/home/clement/repositories/MTG-Arena-Tool/node_modules/@babel/cli/bin/babel.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the MTG-Arena-Tool@4.2.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clement/.npm/_logs/2020-05-19T17_18_33_159Z-debug.log
```
And `/home/clement/.npm/_logs/2020-05-19T17_18_33_159Z-debug.log` which looks pretty much the same:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.5
3 info using node@v14.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle MTG-Arena-Tool@4.2.6~prebuild: MTG-Arena-Tool@4.2.6
6 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
8 verbose lifecycle MTG-Arena-Tool@4.2.6~prebuild: CWD: /home/clement/repositories/MTG-Arena-Tool
9 silly lifecycle MTG-Arena-Tool@4.2.6~prebuild: Args: [ '-c', 'npm run clean:lib' ]
10 silly lifecycle MTG-Arena-Tool@4.2.6~prebuild: Returned: code: 0  signal: null
11 info lifecycle MTG-Arena-Tool@4.2.6~build: MTG-Arena-Tool@4.2.6
12 verbose lifecycle MTG-Arena-Tool@4.2.6~build: unsafe-perm in lifecycle true
13 verbose lifecycle MTG-Arena-Tool@4.2.6~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/clement/repositories/MTG-Arena-Tool/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
14 verbose lifecycle MTG-Arena-Tool@4.2.6~build: CWD: /home/clement/repositories/MTG-Arena-Tool
15 silly lifecycle MTG-Arena-Tool@4.2.6~build: Args: [
15 silly lifecycle   '-c',
15 silly lifecycle   'babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files'
15 silly lifecycle ]
16 silly lifecycle MTG-Arena-Tool@4.2.6~build: Returned: code: 1  signal: null
17 info lifecycle MTG-Arena-Tool@4.2.6~build: Failed to exec build script
18 verbose stack Error: MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:315:20)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:315:20)
18 verbose stack     at maybeClose (internal/child_process.js:1051:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
19 verbose pkgid MTG-Arena-Tool@4.2.6
20 verbose cwd /home/clement/repositories/MTG-Arena-Tool
21 verbose Linux 5.6.11-arch1-1
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
23 verbose node v14.2.0
24 verbose npm  v6.14.5
25 error code ELIFECYCLE
26 error errno 1
27 error MTG-Arena-Tool@4.2.6 build: `babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files`
27 error Exit status 1
28 error Failed at the MTG-Arena-Tool@4.2.6 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 1, true ]
```

(Sorry for big pastes, didn't knew if GitHub would allow for collapsible code snippets).

**Comment by riQQ** [comment]
You can put it in spoilers (see https://gist.github.com/jbsulli/03df3cdce94ee97937ebda0ffef28287).

On which branch and commit are you?

**Comment by Porkepix** [comment]
As said, latest from master, which correspond to `v4.2.6` tag: `0d84a049076fc612f70f92df2a7a02a71817fb92`

**Comment by riQQ** [comment]
Ah it was in the other issue, sorry

**Comment by Porkepix** [comment]
> Ah it was in the other issue, sorry

That's my bad actually, I was sure I said it here, it seems I didn't.

**Comment by Manuel-777** [comment]
Could be related to #1088 ?
Anyway, this seems an issue with npm/node modules more than Tool itself, could be a permissions issue or a missing module in the installation process.

**Comment by Porkepix** [comment]
I thought too when I saw that issue, but the error seems to be different.
Permissions seems unlikely as that's a simple git clone that haven't moved for a long time now, besides regular `git pull`.
A wild guess from me would have been dependencies missing from the installation files but that people regularly working on the project couldn't see because they somehow got the dependencies at some point and don't reinstall from scratch every time by wiping their `node_modules`.

Another reason could be sub-dependencies changing depending on the OS and that main contributors doesn't work with Linux. I don't know what you guys use as main OS and development OS.

**Comment by Manuel-777** [comment]
Well, if the Travis build passes then its probably not the case, could be a problem with your setup specifically (node version maybe?)

**Comment by Porkepix** [comment]
I'm on ArchLinux, therefore using the most recent version of node:
```
$ node --version
v14.3.0
```
I can give you other information on the environment if needed.

**Comment by Manuel-777** [comment]
Any news on this one? I was able to debug/run the tool on Arch this week so im sure it works (also travis passes)

**Comment by Porkepix** [comment]
Still have issues, but different ones now:
After the initial `npm i`, `npm start` shows this:

```
$ npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clement/.npm/_logs/2020-06-26T18_18_06_498Z-debug.log
```
The log file contains this: `$ less /home/clement/.npm/_logs/2020-06-26T18_18_06_498Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:382:12
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16
4 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
5 verbose cwd /home/clement/repositories/MTG-Arena-Tool
6 verbose Linux 5.7.3-arch1-1
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
8 verbose node v14.4.0
9 verbose npm  v6.14.5
10 error missing script: start
11 verbose exit [ 1, true ]
```

And the doc now mention `npm start:all`, which shows this:

```
$ npm start:all

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/clement/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.5 /usr/lib/node_modules/npm

Did you mean this?
    start
```

**Comment by Manuel-777** [comment]
Try using `npm run start:all`, seems its missing on the docs (will update!)

**Comment by Porkepix** [comment]
Okay, it starts now with those parameters.
For my knowledge, why are those additional arguments required and a simple npm start/npm run as before can't work anymore?

A couple of questions slightly out of topic regarding this, but related to start:
- It seems to compile things on every start done this way: I hear fans blow due to CPU usage for a couple dozens of seconds, the time it starts. Is it normal? (I displayed much less things about assets than on the first start though). First start displayed many many things regarding files it was "preparing".
- When on a computer without logs yet, it's doing an infinite loop filling terminal of logs, is it normal?
- When clicking ok on the log window, still without logs, it close the application but reopen it, unlinked to the terminal it was opened from, same thing is it normal?

**Comment by Manuel-777** [comment]
In version 5 we moved the build process to webpack, this is slower than before but gives us better control over what gets into the build, does not compile orphan modules, allows us to minify the code, import assets in js, etc. The reason the build is now split is because building with `npm run build:all` is so slow, if you just want to start the app without changes run `npm run run-electron` instead. The first time you build all assets it tends to be slower so it is to be expected.

If you want to make changes to just one process, you can just build that process and save a ton of build time as well, using the commands like `npm run build:overlay`.

The infinite loop searching for logs is normal, although not ideal.

And it being detached form the terminal is normal too, since the process is restarted.
