### ISSUE TITLE
Games are never read upon completion, only from log

### ISSUE THREAD

**Issue by aragos** [Manuel-777/MTG-Arena-Tool#1169]
I have MTGA Tool running permanently (minimized to menu bar) but it doesn't pick up on games played while open - I need to restart it and have it read the logs.

OS: Mac OS 10.15.6
Tool version: 5.5.2

**Comment by riQQ** [comment]
Can you check the log files for errors or irregularities? Don't just upload it here because it can contain sensitive information.

> Currently MTG Arena Tool logs can be found at the following locations [...]
> on macOS: `~/Library/Logs/MTG-Arena-Tool/`

Source https://mtgatool.com/docs

**Comment by aragos** [comment]
Thanks for taking a look! There appears to be no problem in the log that I can see (here are some probably safe lines from the end):


`main.log`
```
[2020-09-15 16:52:27.747] [debug] IPC LOG: MATCH CREATED: Tue Sep 15 2020 15:38:00 GMT-0400 (Eastern Daylight Time)
[2020-09-15 16:52:27.749] [debug] IPC LOG: vs AdamJitte
[2020-09-15 17:09:08.533] [debug] IPC LOG: MATCH CREATED: Tue Sep 15 2020 17:08:23 GMT-0400 (Eastern Daylight Time)
[2020-09-15 17:09:08.536] [debug] IPC LOG: vs justice17
[2020-09-15 17:21:39.286] [debug] IPC LOG: MATCH CREATED: Tue Sep 15 2020 17:20:52 GMT-0400 (Eastern Daylight Time)
[2020-09-15 17:21:39.287] [debug] IPC LOG: vs Zimdar
[2020-09-15 17:35:20.040] [debug] IPC LOG: MATCH CREATED: Tue Sep 15 2020 17:34:49 GMT-0400 (Eastern Daylight Time)
[2020-09-15 17:35:20.042] [debug] IPC LOG: vs xcver
[2020-09-15 17:41:34.456] [debug] MAIN:  Updating settings
[2020-09-15 17:41:37.878] [debug] MAIN:  Updating settings
```

`renderer.log`
```
[2020-09-15 17:15:59.504] [error] SyntaxError: Unexpected token M in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.json (file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:77434)
    at file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:117651
    at file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:117789
    at qr (file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:126444)
    at file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:116822
    at Object.append (file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:76165)
    at file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:116810
    at async u (file:///Applications/MTG-Arena-Tool.app/Contents/Resources/app.asar/lib/background/index.js:30:116598)
[2020-09-15 17:15:59.507] [error] {
  input: '[UnityCrossThreadLogger]9/15/2020 5:15:59 PM: Match to FCKGUSSS7VDP5AAK6JQ6BJFTSU: GreToClientEvent\n',
  string: '[Message summarized because one or more GameStateMessages exceeded the 50 GameObject or 50 Annotation limit.]'
}
[2020-09-15 17:20:52.008] [debug] 24ee8468-a3c9-4fc9-8ade-e50189c569ea-FCKGUSSS7VDP5AAK6JQ6BJFTSU: [object Object]
[2020-09-15 17:20:52.015] [debug] Save match: [object Object]
[2020-09-15 17:21:05.510] [info] ClientSceneChange [object Object]
[2020-09-15 17:21:06.011] [debug] Select deck: [object Object]
[2020-09-15 17:21:41.763] [debug] Mulligan: 0, 72000,71941,75554,75554,75553,72003,71854
[2020-09-15 17:34:50.012] [debug] 3afbbd95-d438-478a-ace5-5ac2cc02a5a2-FCKGUSSS7VDP5AAK6JQ6BJFTSU: [object Object]
[2020-09-15 17:34:50.019] [debug] Save match: [object Object]
[2020-09-15 17:35:05.794] [info] ClientSceneChange [object Object]
[2020-09-15 17:35:06.265] [debug] Select deck: [object Object]
[2020-09-15 17:35:24.265] [debug] Mulligan: 0, 71950,75554,71941,71941,72021,71953,75553
[2020-09-15 17:35:42.263] [debug] Mulligan: 1, 75554,71950,71849,71941,71938,71940,75554
[2020-09-15 17:35:46.763] [debug] Mulligan: 2, 71928,72031,71859,71849,75555,71829,75555
[2020-09-15 17:40:59.517] [debug] 54a1172c-5b2f-42e1-bd3f-60d1361c7fd6-FCKGUSSS7VDP5AAK6JQ6BJFTSU: [object Object]
[2020-09-15 17:40:59.525] [debug] Save match: [object Object]
[2020-09-15 17:41:13.272] [info] ClientSceneChange [object Object]
[2020-09-15 17:41:13.769] [debug] Select deck: [object Object]
[2020-09-15 17:41:18.516] [info] ClientSceneChange [object Object]
```
```
