### ISSUE TITLE
AppendTo Not Function

### ISSUE THREAD

**Issue by letmecodeforyou-HF** [Manuel-777/MTG-Arena-Tool#331]
```
TypeError: but.appendTo is not a function
    at openHomeTab (C:\Users\user\MTG-Arena-Tool\window_main\home.js:106:9)
    at HTMLDivElement.<anonymous> (file:///C:/Users/user/MTG-Arena-Tool/window_main/renderer.js:975:13)
    at HTMLDivElement.dispatch (file:///C:/Users/user/MTG-Arena-Tool/shared/jquery-3.3.1.min.js:2:41772)
    at HTMLDivElement.y.handle (file:///C:/Users/user/MTG-Arena-Tool/shared/jquery-3.3.1.min.js:2:39791)
```

---

MTG-Arena-Tool 2.5.1
Electron 3.1.9
win32 10.0.17763
Locale: en-US

**Comment by letmecodeforyou-HF** [comment]
@Manuel-777 Is there a solution to this? The home page literally doesn't work.

**Comment by Manuel-777** [comment]
[dd0386b](https://github.com/Manuel-777/MTG-Arena-Tool/commit/dd0386b67b1b8c666ededfa2d119f60765ad53f2) fixed it, pulling latest master should work. If you are running latest pre-release installer I will push a new version tonight.
