### ISSUE TITLE
Unhandled Error TypeError: topWildcards.forEach is not a function

### ISSUE THREAD

**Issue by d3wF1nk** [Manuel-777/MTG-Arena-Tool#366]
Hi, when i run it for the first time with command `npm start` after login i have this error message:
```
Unhandled Error
TypeError: topWildcards.forEach is not a function
    at openHomeTab (C:/Users/Utente/workGAME/MTGAtracker/window_main/home.js:315:18)
    at EventEmitter.<anonymous> (file:///C:/Users/Utente/workGAME/MTGAtracker/window_main/renderer.js:534:5)
```

**Comment by Manuel-777** [comment]
Fixed, thanks for the report! :)
