### ISSUE TITLE
when clicking on the decks

### ISSUE THREAD

**Issue by jtbai** [Manuel-777/MTG-Arena-Tool#579]
```
TypeError: _deck.rank.sort is not a function
    at deckLoad (/home/jtbai/Programs/js/MTG-Arena-Tool/window_main/explore.js:646:14)
    at /home/jtbai/Programs/js/MTG-Arena-Tool/window_main/explore.js:542:31
    at Array.forEach (<anonymous>)
    at renderData (/home/jtbai/Programs/js/MTG-Arena-Tool/window_main/explore.js:542:6)
    at setExploreDecks (/home/jtbai/Programs/js/MTG-Arena-Tool/window_main/explore.js:525:3)
    at EventEmitter.<anonymous> (file:///home/jtbai/Programs/js/MTG-Arena-Tool/window_main/renderer.js:234:5)
    at EventEmitter.emit (events.js:194:13)
```

---

MTG-Arena-Tool 2.9.4
Electron 5.0.1
linux 4.18.0-25-generic
Locale: en-GB

**Comment by Manuel-777** [comment]
What event/filter was this on?
