### ISSUE TITLE
Clicking a deck or match throw an exception message

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#649]
Context informations:
Built from source (current master)
I currently try and move between different window managers or desktop environment. Current bug report is about issues I got with KDE/Plasma, and I guess X.org.

Clicking a deck in the "my decks" view or a match in the "history" view currently throw the current exception:

```
Unhandled Error
TypeError: _cardTypes.default.cardType is not a function
    at /home/clement/repositories/MTG-Arena-Tool/lib/window_main/renderer-util.js:227:41
    at arrayAggregator (/home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:497:34)
    at Function.groupBy (/home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:4823:16)
    at /home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:4368:28
    at arrayReduce (/home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:4367:14)
    at LodashWrapper.wrapperValue (/home/clement/repositories/MTG-Arena-Tool/node_modules/lodash/lodash.js:9050:14)
    at drawDeck (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/renderer-util.js:252:6)
    at renderSeat (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/match-details.js:339:30)
    at openMatch (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/match-details.js:125:3)
    at ListItem.handleOpenMatch [as onClickCallback] (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/history.js:238:31)
    at HTMLDivElement.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/list-item.js:70:12)
    at HTMLDivElement.sentryWrapped (/home/clement/repositories/MTG-Arena-Tool/node_modules/@sentry/browser/dist/index.js:3204:27)
```

The error seems to be the same in both cases.

**Comment by Lego6245** [comment]
Hey, thanks for all your issue opening. This specific one we know about, and is resolved by re-running `npm i`, as we've added a few dependencies with some recent changes. Just make sure you're fully synced to master and rerun `npm i` and you should be fine.

**Comment by Porkepix** [comment]
> Hey, thanks for all your issue opening. This specific one we know about, and is resolved by re-running `npm i`, as we've added a few dependencies with some recent changes. Just make sure you're fully synced to master and rerun `npm i` and you should be fine.

@Lego6245  I guess `npm i` is a shortcut for `npm install`?
Actually this install from master was only 24 to 36H old and was maybe only one or two commits late on master, seems it was still too much though: it indeed fixed the issue, although transition is not that smooth. But I should run more tests depending on environment, fresh boot and so on.

To update completely and have nothing else remaining, is a `git reset --hard`, `rm -rf node_modules` and rerun `npm install` enough?
Starting with `npm start` seems to lead to complete re-read of logs while my stable install on Windows seems to be able to catch-up on an already up-to-date or almost state, is it related?

Also, while we are at dependencies, I guess you already know about it, but npm complains about deprecations and high severity vulnerabilities.

```
[clement@T470-clement MTG-Arena-Tool]$ npm i

> MTG-Arena-Tool@2.12.3 postinstall /home/clement/repositories/MTG-Arena-Tool
> install-app-deps

  • please use as subcommand: electron-builder install-app-deps
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
  • electron-builder version=20.40.2
  • loaded configuration file=package.json ("build" field)
  • no native production dependencies
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 890665 packages in 16.21s
found 22 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

(And the audit fails):
```
[clement@T470-clement MTG-Arena-Tool]$ npm audit
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/clement/.npm/_logs/2019-10-21T17_30_19_337Z-debug.log
```

Closing the issue, as indeed fixed by your comment.
