### ISSUE TITLE
"path" argument must be of type string

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#727]
Just updated on a Linux computer the application with repo's master, application runs fine, however it throws this exception in terminal:

```
$ npm start

> MTG-Arena-Tool@2.13.0 start /home/clement/repositories/MTG-Arena-Tool
> npm run babel && electron .


> MTG-Arena-Tool@2.13.0 babel /home/clement/repositories/MTG-Arena-Tool
> npm run tsc && babel src --extensions ".ts,.tsx,.js,.jsx" --out-dir lib --copy-files


> MTG-Arena-Tool@2.13.0 tsc /home/clement/repositories/MTG-Arena-Tool
> tsc

[BABEL] Note: The code generator has deoptimised the styling of /home/clement/repositories/MTG-Arena-Tool/src/window_background/messages_pb.js as it exceeds the max of 500KB.
Successfully compiled 97 files with Babel.
linux
Installing Devtron from /home/clement/repositories/MTG-Arena-Tool/node_modules/devtron
Uncaught exception;
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:1037:7)
    at getManifestFromPath (/home/clement/repositories/MTG-Arena-Tool/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:35:34)
    at Function.BrowserWindow.addExtension (/home/clement/repositories/MTG-Arena-Tool/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:376:22)
    at Function.BrowserWindow.addDevToolsExtension (/home/clement/repositories/MTG-Arena-Tool/node_modules/electron/dist/resources/electron.asar/browser/chrome-extension.js:408:40)
    at App.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/lib/main.js:92:37)
    at App.emit (events.js:199:15)
MAIN:  Initializing
```

**Comment by Manuel-777** [comment]
fixed in ae5b5a649f3a9831e679f160d42cbd8de899aba8 (develop)
