### ISSUE TITLE
Unusable tabs with decks containing Historic Anthology 2 cards

### ISSUE THREAD

**Issue by budu** [Manuel-777/MTG-Arena-Tool#921]
Decks and collection tabs are not usable since the introduction of Historic Anthology 2 cards.

Stacktrace:
```
TypeError: Cannot read property 'name' of undefined
    at ...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\labels.js:833:19
    at Array.forEach (<anonymous>)
    at ...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\labels.js:830:19
    at Array.forEach (<anonymous>)
    at onLabelInDeckUpdateDeckV3 (...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\labels.js:826:18)
    at entrySwitch (...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-watcher.js:284:47)
    at onLogEntryFound (...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-watcher.js:179:9)
    at ...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-watcher.js:93:42
    at Object.append (...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-decoder\arena-log-decoder.js:60:11)
    at read (...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-watcher.js:93:20)
onLogEntryFound @ ...\Programs\MTG-Arena-Tool\resources\app.asar\lib\window_background\arena-log-watcher.js:199
```

**Comment by laurensbl** [comment]
Hmm, I bought those Anthology 2 cards yesterday and since yesterday my Economy tab stopped working (doesn't show anything, completely empty).

I wonder if there's a correlation here.

Decks and Collection tab are functioning properly btw. Fyi, didn't use any of those  Ant 2 cards in a deck yet.

**Comment by Manuel-777** [comment]
Hi there!

I believe this was because of the cards were not in the database yet, is it ok now?

**Comment by budu** [comment]
Yes, everything is working now.

**Comment by laurensbl** [comment]
All OK here too, Enonomy tab is working again.
