### ISSUE TITLE
Dependency error - electron-react-devtools

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#949]
When running MTG-Arena-Tool from terminal, we get the exception visible below. Being not knowledgeable with JS/NodeJS, I can't be sure if the issue origins from a call in this repo source code, or drectly from another dependency, therefore if any issue belongs here or in one of those dependencies, so I prefered to open it here just in case. If you think it have to be opened in one dependency, if you could point out which one, I can open the corresponding issue.

```
Error: ENOENT: no such file or directory, open '/home/clement/repositories/MTG-Arena-Tool/node_modules/electron-react-devtools/manifest.json'
    at Object.openSync (fs.js:440:3)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.readFileSync (fs.js:342:35)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
    at getManifestFromPath (electron/js2c/browser_init.js:4026:26)
    at Function.BrowserWindow.addExtension (electron/js2c/browser_init.js:4448:22)
    at Function.BrowserWindow.addDevToolsExtension (electron/js2c/browser_init.js:4480:40)
    at App.<anonymous> (electron/js2c/browser_init.js:4509:23)
```

**Comment by Porkepix** [comment]
Closing it dodesn't seem to be here on latest versions.
