### ISSUE TITLE
My Decks gives a black window in 4.0.0

### ISSUE THREAD

**Issue by qiemem** [Manuel-777/MTG-Arena-Tool#974]
For example:

![Screenshot from 2020-04-03 10-19-03](https://user-images.githubusercontent.com/28215/78387723-ab6edb00-7594-11ea-89b3-9c66a8d95114.png)

![Screenshot from 2020-04-03 10-19-07](https://user-images.githubusercontent.com/28215/78387747-b1fd5280-7594-11ea-9028-0cbf22dff1c4.png)

Running Fedora 31 with Gnome 3.34.4. Also, everytime I start 3.0.7 or 3.0.8, it auatomatically downloads 4.0.0 and runs it instead, so I can't confirm that this started with 4.0.0 (not sure if there's a way to supress this).

BTW, for others experiencing this issue, if you can't seem to start up mtga tool without getting a black screen, click on settings in the login screen before logging in. Then, when you login, you'll go to the settings tab instead of my decks.

**Comment by TroubiCZ** [comment]
+1, but running on Windows 10. Exactly the same issue & workaround.

**Comment by qiemem** [comment]
Good to know! Edited title to reflect that it's not just Linux.

**Comment by pchclx** [comment]
+1 here.  Windows 10

**Comment by Manuel-777** [comment]
Hello! Anyone with this issue can debug pressing `Shift + Alt + D` and looking into one of the consoles for red errors (yellows are just warnings, unimportant)
A screenshof of the errors should be enough .

**Comment by qiemem** [comment]
![Screenshot from 2020-04-03 13-03-19](https://user-images.githubusercontent.com/28215/78400432-8b96e180-75ab-11ea-941b-cc0886ea5259.png)

Here you go!

**Comment by Porkepix** [comment]
If this may help, version `4.0.1` seems to have a similar issue that resulted in the following exception in a popup window:
```
Unhandled Error
TypeError: colors.map is not a function
    at ColorsCell (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/components/tables/cells.js:67:86)
    at renderWithHooks (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:14825:18)
    at mountIndeterminateComponent (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:17505:13)
    at beginWork (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:18629:16)
    at HTMLUnknownElement.callCallback (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at HTMLUnknownElement.sentryWrapped (/home/clement/repositories/MTG-Arena-Tool/node_modules/@sentry/browser/dist/helpers.js:74:23)
    at Object.invokeGuardedCallbackDev (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:23234:7)
    at performUnitOfWork (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:22185:12)
    at workLoopSync (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:22161:22)
    at performSyncWorkOnRoot (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:21787:9)
    at /home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11111:24
    at unstable_runWithPriority (/home/clement/repositories/MTG-Arena-Tool/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11061:10)
    at flushSyncCallbackQueueImpl (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11106:7)
    at flushSyncCallbackQueue (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11094:3)
    at discreteUpdates$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:21924:7)
    at discreteUpdates (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:1071:12)
    at dispatchDiscreteEvent (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:4168:3)
    at HTMLDocument.sentryWrapped (/home/clement/repositories/MTG-Arena-Tool/node_modules/@sentry/browser/dist/helpers.js:74:23)
```
