### ISSUE TITLE
[Linux] MTG-Arena-Tool crashing on startup with v.4.0.2

### ISSUE THREAD

**Issue by Porkepix** [Manuel-777/MTG-Arena-Tool#977]
Got lucky catching the exception with keyboard as buttons were out of the screen:

```
TypeError: colors.map is not a function
    at ColorsCell (/home/clement/repositories/MTG-Arena-Tool/lib/window_main/components/tables/cells.js:67:86)
    at renderWithHooks (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:14825:18)
    at mountIndeterminateComponent (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:17505:13)
    at beginWork (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:18629:16)
    at HTMLUnknownElement.callCallback (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:188:14)
    at HTMLUnknownElement.sentryWrapped (/home/clement/repositories/MTG-Arena-Tool/node_modules/@sentry/browser/dist/helpers.js:74:23)
    at Object.invokeGuardedCallbackDev (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:237:16)
    at invokeGuardedCallback (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:292:31)
    at beginWork$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:23234:7)
    at performUnitOfWork (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:22185:12)
    at workLoopSync (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:22161:22)
    at performSyncWorkOnRoot (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:21787:9)
    at /home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11111:24
    at unstable_runWithPriority (/home/clement/repositories/MTG-Arena-Tool/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11061:10)
    at flushSyncCallbackQueueImpl (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11106:7)
    at flushSyncCallbackQueue (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:11094:3)
    at batchedUpdates$1 (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-dom/cjs/react-dom.development.js:21893:7)
    at Object.notify (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-redux/lib/utils/Subscription.js:25:7)
    at Subscription.notifyNestedSubs (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-redux/lib/utils/Subscription.js:98:20)
    at Subscription.handleChangeWrapper (/home/clement/repositories/MTG-Arena-Tool/node_modules/react-redux/lib/utils/Subscription.js:103:12)
    at Object.dispatch (/home/clement/repositories/MTG-Arena-Tool/node_modules/redux/lib/redux.js:228:7)
    at e (<anonymous>:1:40553)
    at /home/clement/repositories/MTG-Arena-Tool/node_modules/@reduxjs/toolkit/dist/redux-toolkit.cjs.development.js:172:22
    at /home/clement/repositories/MTG-Arena-Tool/node_modules/redux-thunk/lib/index.js:14:16
    at Object.dispatch (/home/clement/repositories/MTG-Arena-Tool/node_modules/redux-immutable-state-invariant/dist/index.js:55:32)
    at Object.dispatch (<anonymous>:1:28545)
    at EventEmitter.<anonymous> (/home/clement/repositories/MTG-Arena-Tool/lib/shared-redux/sharedRedux.js:62:13)
    at EventEmitter.emit (events.js:210:5)
    at EventEmitter.emit (domain.js:476:20)
    at Object.onMessage (electron/js2c/renderer_init.js:2188:16)
```

---

MTG-Arena-Tool 4.0.2
Electron 8.1.1
linux 5.5.13-arch2-1
Locale: en-US

**Comment by Manuel-777** [comment]
Same as describen in #974 , could you share your `.db` file and a sample log to replicate?
dont share here, send at `mtgatool@gmail.com`

**Comment by Porkepix** [comment]
Sent right now. As explained in the email, issue disappeared once I wiped the `~/.config/MTG-Arena-Tool/` directory, so it definitely seems to be an issue within the .db file I sent you over that might have had some upgrade issue at some point.
