### ISSUE TITLE
Overlay doesn't show

### ISSUE THREAD

**Issue by riQQ** [Manuel-777/MTG-Arena-Tool#979]
Version 4.0.2

Errors in the overlay console:
```
3C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14890 Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at renderWithHooks (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14890:13)
    at updateFunctionComponent (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17058:20)
    at beginWork (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18643:16)
    at HTMLUnknownElement.callCallback (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237:16)
    at invokeGuardedCallback (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292:31)
    at beginWork$1 (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23234:7)
    at performUnitOfWork (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22188:12)
    at workLoopSync (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22161:22)
    at performSyncWorkOnRoot (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21787:9)
```

```
3C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19560 

The above error occurred in the <CardTile> component:
    in CardTile (created by DeckList)
    in div (created by DeckList)
    in DeckList (created by MatchElements)
    in div (created by MatchElements)
    in MatchElements (created by OverlayWindowlet)
    in div (created by OverlayWindowlet)
    in OverlayWindowlet (created by OverlayController)
    in div (created by OverlayController)
    in OverlayController
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

```
logCapturedError @ C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:19560
C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:11124 Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
    at renderWithHooks (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:14890:13)
    at updateFunctionComponent (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:17058:20)
    at beginWork (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:18643:16)
    at HTMLUnknownElement.callCallback (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:237:16)
    at invokeGuardedCallback (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:292:31)
    at beginWork$1 (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:23234:7)
    at performUnitOfWork (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22188:12)
    at workLoopSync (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:22161:22)
    at performSyncWorkOnRoot (C:\Users\<WindowsUser>\AppData\Local\Programs\MTG-Arena-Tool\resources\app.asar\node_modules\react-dom\cjs\react-dom.development.js:21787:9)
```

**Comment by riQQ** [comment]
This was fixed in 4.0.3.
